'use client';

import { useEffect, useRef } from 'react';
import ExperienceIcon from '@/components/ExperienceIcon';

export default function EditableImmersiveHero({ hero }) {
  const root = useRef(null);
  useEffect(() => {
    const element = root.current; const preference = window.matchMedia('(prefers-reduced-motion: reduce)'); let frame = 0; const clamp = (value) => Math.min(1, Math.max(0, value));
    const update = () => { frame = 0; const bounds = element.getBoundingClientRect(); const progress = preference.matches ? 0 : clamp(-bounds.top / Math.max(1, bounds.height - window.innerHeight)); element.style.setProperty('--journey', progress); element.style.setProperty('--zoom', 1 + progress * 0.14); element.style.setProperty('--intro-opacity', 1 - clamp(progress / 0.3)); element.style.setProperty('--intro-y', `${progress * -110}px`); element.style.setProperty('--scene-two', clamp((progress - 0.22) / 0.22)); element.style.setProperty('--scene-three', clamp((progress - 0.62) / 0.22)); element.style.setProperty('--chapter-two', clamp((progress - 0.3) / 0.13) * (1 - clamp((progress - 0.58) / 0.1))); element.style.setProperty('--chapter-three', clamp((progress - 0.73) / 0.15)); element.dataset.chapter = progress < 0.34 ? '1' : progress < 0.74 ? '2' : '3'; };
    const schedule = () => { if (!frame) frame = window.requestAnimationFrame(update); }; update(); window.addEventListener('scroll', schedule, { passive: true }); window.addEventListener('resize', schedule); preference.addEventListener('change', schedule);
    return () => { window.cancelAnimationFrame(frame); window.removeEventListener('scroll', schedule); window.removeEventListener('resize', schedule); preference.removeEventListener('change', schedule); };
  }, []);
  return <section className="immersive-journey" id="inicio" ref={root} aria-label="Explore um novo jeito de morar"><div className="immersive-stage"><div className="journey-images" aria-hidden="true">{hero.scenes.map((scene, index) => <picture key={scene.desktop} className={`journey-image journey-image-${index + 1}`}>{scene.mobile && <source media="(max-width: 760px)" srcSet={scene.mobile} />}<img src={scene.desktop} alt={scene.alt} fetchPriority={index === 0 ? 'high' : 'low'} decoding="async" /></picture>)}</div><div className="journey-shade" /><div className="journey-orbit" aria-hidden="true"><span /><span /></div><div className="journey-coordinate" aria-hidden="true">12°58′ S &nbsp; 38°30′ W <span>BAHIA, BRASIL</span></div><div className="journey-intro"><p className="experience-kicker"><span className="signal-dot" /> {hero.kicker}</p><h1><span className="title-mask"><span>{hero.titleLineOne}</span></span><span className="title-mask"><span>{hero.titleLineTwo}</span></span></h1><div className="journey-intro-bottom"><p>{hero.intro.split('\n').map((line, index) => <span key={index}>{line}{index < hero.intro.split('\n').length - 1 && <br />}</span>)}</p><a href="#busca" className="experience-button">{hero.ctaLabel} <span><ExperienceIcon /></span></a></div></div><div className="journey-chapter chapter-two" aria-hidden="true"><span className="experience-kicker">02 / SINTA O ESPAÇO</span><p>A vida pede<br /><em>mais espaço.</em></p></div><div className="journey-chapter chapter-three" aria-hidden="true"><span className="experience-kicker">03 / IMAGINE O PRÓXIMO CAPÍTULO</span><p>O seu lugar.<br /><em>Do seu jeito.</em></p></div><div className="journey-bottom"><a href="#busca" className="scroll-invitation"><span><ExperienceIcon direction="down" /></span> ROLE PARA EXPLORAR</a><div className="journey-index" aria-hidden="true">{hero.scenes.map((scene, index) => <span key={scene.desktop} className={`journey-step step-${index + 1}`}><b>0{index + 1}</b><span>{scene.label}</span></span>)}</div><span className="journey-photo-note">Imagens de inspiração</span></div><div className="journey-progress" aria-hidden="true" /></div></section>;
}
