import Nav from '@/components/Nav';
import { SimpleFooter } from '@/components/Footer';
import WhatsAppFloat from '@/components/WhatsAppFloat';

export default function GenericLaunchPage({ launch, property }) {
  const photos = property?.fotos || [];
  const description = launch.description || 'Um novo endereço pensado para viver com mais intenção.';
  return <div className="launch-page site-identity"><Nav active="lancamentos" launchOnly /><main><section className="launch-hero"><img src={photos[0] || 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85'} alt="" /><div className="launch-hero-shade" /><div className="wrap launch-hero-content"><span className="launch-label">Lançamento</span><h1>{launch.title}</h1><p>{description}</p><div className="launch-hero-actions"><a className="experience-button" href="#sobre">Conhecer o projeto</a><button className="button" type="button" data-popup="interesse" data-property={launch.title} data-modalities="venda">Quero conhecer</button></div></div></section><section className="launch-intro" id="sobre"><div className="wrap"><span className="launch-kicker">O EMPREENDIMENTO</span><div className="launch-intro-grid"><h2>Um novo começo,<br /><em>no endereço certo.</em></h2><p>{description}</p></div>{launch.highlights && <div className="launch-numbers"><div><strong>{launch.highlights}</strong><span>Informações do empreendimento</span></div></div>}</div></section>{photos.length > 1 && <section className="launch-gallery"><div className="wrap"><div className="launch-section-heading"><span className="launch-kicker">GALERIA</span><h2>Veja o<br /><em>projeto.</em></h2></div><div className="launch-leisure-images">{photos.slice(0, 3).map((photo) => <figure key={photo}><img src={photo} alt={launch.title} /></figure>)}</div></div></section>}<section className="launch-cta"><div className="wrap"><div><span>{launch.location || 'CASA COM LEO / LANÇAMENTOS'}</span><h2>Vamos conversar<br />sobre esse começo?</h2></div><button className="button" type="button" data-popup="interesse" data-property={launch.title} data-modalities="venda">Quero saber mais</button></div></section></main><SimpleFooter /><WhatsAppFloat minimalOnMobile /></div>;
}
