import Nav from '@/components/Nav';
import { SimpleFooter } from '@/components/Footer';
import WhatsAppFloat from '@/components/WhatsAppFloat';

const ASSET = 'https://azinunes.com.br/empreendimentos/reserva-do-sol/rds';
const PHOTOS = [
  ['hero-piscina-fachada.webp', 'Piscina e fachadas do Reserva do Sol'],
  ['fachada-acesso.webp', 'Acesso do Reserva do Sol'],
  ['piscina-entardecer.webp', 'Piscina do Reserva do Sol'],
  ['quiosque-area-gourmet.webp', 'Quiosque com área gourmet'],
  ['parque-infantil.webp', 'Parque infantil'],
  ['interior-living.webp', 'Living integrado'],
];

export default function ReservaDoSolPage() {
  const photo = (name) => `${ASSET}/${name}`;
  return <div className="launch-page site-identity reserva-do-sol-page"><Nav active="lancamentos" launchOnly /><main>
    <section className="launch-hero"><img src={photo(PHOTOS[0][0])} alt={PHOTOS[0][1]} fetchPriority="high" /><div className="launch-hero-shade" /><div className="wrap launch-hero-content"><span className="launch-label">Lançamento · Itacimirim, Bahia</span><h1>Reserva do<br /><em>Sol.</em></h1><p>Apartamentos de 2 suítes para viver entre águas cristalinas, natureza e tempo de qualidade.</p><div className="launch-hero-actions"><a className="experience-button" href="#projeto">Explorar o projeto</a><button className="button" type="button" data-popup="interesse" data-property="Reserva do Sol" data-modalities="venda">Quero conhecer</button></div></div></section>
    <nav className="launch-anchor-nav" aria-label="Navegação do Reserva do Sol"><div className="wrap"><a href="#projeto">Projeto</a><a href="#residencias">Residências</a><a href="#lazer">Lazer</a><a href="#localizacao">Localização</a><a href="#galeria">Galeria</a></div></nav>
    <section className="launch-intro" id="projeto"><div className="wrap"><span className="launch-kicker">LAR E LAZER</span><div className="launch-intro-grid"><h2>Seu refúgio<br /><em>em Itacimirim.</em></h2><p>Um condomínio acolhedor, pensado para quem procura tranquilidade, praticidade e uma relação mais próxima com a natureza.</p></div><div className="launch-numbers"><div><strong>32</strong><span>unidades</span></div><div><strong>2</strong><span>suítes por unidade</span></div><div><strong>2</strong><span>vagas por unidade</span></div><div><strong>63–67</strong><span>m² privativos</span></div></div></div></section>
    <section className="launch-statements"><div className="wrap"><article><div><span>01</span><h3>A natureza como ponto de partida.</h3><p>Águas cristalinas, vegetação exuberante e a tranquilidade de Itacimirim fazem parte da experiência desde a chegada.</p></div><img src={photo(PHOTOS[1][0])} alt={PHOTOS[1][1]} /></article><article><div><span>02</span><h3>Conforto pensado de dentro para fora.</h3><p>Plantas com 2 suítes, áreas externas e versões térreas com jardim para morar ou investir com leveza.</p></div><img src={photo(PHOTOS[5][0])} alt={PHOTOS[5][1]} /></article><article><div><span>03</span><h3>Lazer que prolonga a casa.</h3><p>Piscina, área gourmet, parque infantil, quadra de areia, bicicletário e estacionamento privativo.</p></div><img src={photo(PHOTOS[2][0])} alt={PHOTOS[2][1]} /></article></div></section>
    <section className="launch-residences" id="residencias"><div className="wrap launch-two-column"><div><span className="launch-kicker">RESIDÊNCIAS</span><h2>Quatro metragens,<br /><em>duas formas de viver.</em></h2><p>Apartamentos de 63,31 m² a 67,38 m², com opções térreas que integram jardim e área externa privativa.</p></div><div className="launch-plan"><span>APARTAMENTOS</span><strong>63,31 a 67,38 m²</strong><p>2 suítes · 2 vagas · opções com jardim</p><ul><li>Plantas lateral e do meio</li><li>Térreo com jardim</li><li>Pavimento superior</li><li>Ambientes para morar ou investir</li></ul></div></div></section>
    <section className="launch-leisure" id="lazer"><div className="wrap"><span className="launch-kicker">LAZER & DIFERENCIAIS</span><div className="launch-leisure-head"><h2>Lar e lazer<br /><em>em equilíbrio.</em></h2><p>Espaços que prolongam a experiência de morar com qualidade de vida, encontro e movimento.</p></div><div className="launch-leisure-images"><figure><img src={photo(PHOTOS[2][0])} alt={PHOTOS[2][1]} /><figcaption><span>Lazer aquático</span>Piscina</figcaption></figure><figure><img src={photo(PHOTOS[3][0])} alt={PHOTOS[3][1]} /><figcaption><span>Convivência</span>Quiosque gourmet</figcaption></figure><figure><img src={photo(PHOTOS[4][0])} alt={PHOTOS[4][1]} /><figcaption><span>Família</span>Parque infantil</figcaption></figure></div></div></section>
    <section className="launch-location" id="localizacao"><div className="wrap launch-location-grid"><div><span className="launch-kicker">LOCALIZAÇÃO</span><h2>Um refúgio<br /><em>em Itacimirim.</em></h2><p>Um destino de águas cristalinas e natureza exuberante para quem busca desacelerar sem abrir mão de praticidade.</p></div><img src={photo(PHOTOS[1][0])} alt={PHOTOS[1][1]} /></div></section>
    <section className="launch-gallery" id="galeria"><div className="wrap"><div className="launch-section-heading"><span className="launch-kicker">GALERIA</span><h2>Perspectivas<br /><em>do projeto.</em></h2></div><div className="launch-leisure-images">{PHOTOS.slice(0, 3).map(([src, alt]) => <figure key={src}><img src={photo(src)} alt={alt} /></figure>)}</div></div></section>
    <section className="launch-technical"><div className="wrap"><span className="launch-kicker">FICHA TÉCNICA</span><div className="launch-tech-grid"><div><span>Localização</span><p>Itacimirim, Bahia</p></div><div><span>Tipo</span><p>Apartamentos residenciais com 2 suítes</p></div><div><span>Realização</span><p>Azinunes Construções & Incorporações · Beta Engenharia</p></div><div><span>Arquitetura e interiores</span><p>Valença & Valença</p></div><div><span>Unidades</span><p>32</p></div><div><span>Metragens</span><p>63,31 m² · 64,11 m² · 66,57 m² · 67,38 m²</p></div></div></div></section>
    <section className="launch-cta"><div className="wrap"><div><span>RESERVA DO SOL · ITACIMIRIM</span><h2>Seu refúgio pode<br />começar aqui.</h2></div><button className="button" type="button" data-popup="interesse" data-property="Reserva do Sol" data-modalities="venda">Quero saber mais</button></div></section>
  </main><SimpleFooter /><WhatsAppFloat minimalOnMobile /></div>;
}
